### ISSUE TITLE
Non-descriptive SocketException

### ISSUE THREAD

**Issue by jkrug16** [PLCnext/CSharpExamples#11]
We're getting occasional SocketExceptions when trying to listen on a TCP port from Eclr.
Jan 2 19:35:22 axcf3152 Arp.System.Application: Eclr INFO - Loaded IO config 'GS0'. 264 sensors, 95 actuators.
Jan 2 19:35:22 axcf3152 Arp.System.Application: Eclr INFO - Loaded 0 sequences. Basic sequence validation passed.
Jan 2 19:35:22 axcf3152 Arp.System.Application: Eclr INFO - Validating seq config IO channels...
Jan 2 19:35:22 axcf3152 Arp.System.Application: Eclr INFO - IO config references following channels: ai04-3-2, ai04-2-1, ai04-6-4, ai04-6-5, ai04-6-3, ai04-6-2, ai04-6-6, ai10-4-5, ai10-3-5, ai10-2-8, ai10-4-7, ai10-2-6, ai10-2-4, ai10-2-4, ai04-4-5, ai04-4-3, ai04-3-1, ai04-3-3, ai04-3-7, ai04-3-5, ai04-6-1, ai07-2-7, rtd-iol2-1, rtd-iol2-2, ai10-1-2, ai10-1-1, ai10-4-2, ai10-4-4, rtd-iol1-1, ai10-3-7, ai10-4-8, ai10-4-1, ai10-4-3, rtd-iol1-2, ai10-4-4, ai10-4-6, ai10-3-2, ai10-3-4, ai07-5-2, ai07-2-1, ai07-2-3, ai07-2-2, ai07-2-4, ai07-3-2, ai07-3-1, ai07-6-1, ai07-6-2, ai04-4-4, ai04-2-7, ai04-1-1, ai04-1-3, ai04-1-5, ai04-1-7, ai04-1-2, ai04-1-4, ai13-1-3, ai10-6-1, ai10-6-6, ai10-6-6, ai10-6-2, ai10-6-7, ai10-6-5, ai04-5-1, ai04-5-3, ai13-1-1, ai04-5-5, ai13-1-5, ai04-1-6, rtd-iol3-1, ai13-1-7, ai13-1-2, rtd-iol3-2, rtd-iol3-3, ai13-1-4, ai10-6-4, rtd-iol3-4, ai13-1-6, ai10-6-3, dio05-5-1-4, dio05-5-1-2, dio06-2-3-4, dio06-2-3-2, dio06-2-1-4, dio06-2-1-2, dio09-2-4-2, dio09-2-4-4, dio09-4-1-4, dio09-4-1-2, dio09-4-3-4, dio09-4-3-2, dio03-3-4-4, dio03-3-4-2, dio03-5-3-4, dio03-5-3-2, dio03-2-1-2, dio03-2-1-4, dio03-2-2-2, dio03-2-2-4, dio03-2-3-2, dio03-2-3-4, dio09-1-4-4, dio09-1-4-2, dio08-4-1-4, dio08-4-1-2, dio08-5-2-4, dio08-5-2-2, dio09-3-3-4, dio09-3-3-2, dio09-2-1-4, dio09-2-1-2, dio08-5-3-4, dio08-5-3-2, dio08-5-1-4, dio08-5-1-2, dio06-3-2-4, dio06-3-2-2, dio06-2-2-4, dio06-2-2-2, dio06-5-4-4, dio06-5-4-2, dio06-6-3-4, dio06-6-3-2, dio08-1-1-4, dio08-1-1-2, dio06-6-4-4, dio06-6-4-2, dio08-1-2-4, dio08-1-2-2, dio06-4-2-4, dio06-4-2-2, dio06-4-3-4, dio06-4-3-2, dio06-3-3-4, dio06-3-3-2, dio06-4-1-4, dio06-4-1-2, dio06-4-4-4, dio06-4-4-2, dio05-1-4-4, dio05-1-4-2, dio05-1-1-4, dio05-1-1-2, dio05-2-2-4, dio05-2-2-2, dio03-5-2-4, dio03-5-2-2, dio03-4-3-4, dio03-4-3-2, dio05-1-3-4, dio05-1-3-2, dio05-2-3-4, dio05-2-3-2, dio05-1-2-4, dio05-1-2-2, dio05-2-4-4, dio05-2-4-2, dio05-2-1-4, dio05-2-1-2, dio09-4-2-4, dio09-4-2-2, dio09-4-4-4, dio09-4-4-2, dio09-1-2-2, dio09-1-2-4, dio09-1-3-2, dio09-1-3-4, dio03-5-1-4, dio03-5-1-2, dio03-5-4-4, dio03-5-4-2, dio09-1-1-4, dio09-1-1-2, dio09-3-1-4, dio09-3-1-2, dio09-3-4-4, dio09-3-4-2, dio08-4-2-4, dio08-4-2-2, dio09-2-3-4, dio09-2-3-2, dio09-3-2-4, dio09-3-2-2, dio08-4-4-4, dio08-4-4-2, dio08-6-2-4, dio08-6-2-2, dio03-6-3-4, dio03-6-3-2, dio05-6-1-4, dio05-6-1-2, dio05-6-2-4, dio05-6-2-2, dio03-6-4-4, dio03-6-4-2, dio03-6-1-4, dio03-6-1-2, dio06-6-1-4, dio06-6-1-2, dio05-4-3-4, dio05-4-3-2, dio05-4-4-4, dio05-4-4-2, dio03-6-2-4, dio03-6-2-2, dio05-6-3-4, dio05-6-3-2, dio06-6-2-4, dio06-6-2-2, dio05-5-2-4, dio05-5-2-2, dio06-5-1-4, dio06-5-1-2, dio06-5-2-4, dio06-5-2-2, dio06-2-4-4, dio06-2-4-2, dio03-3-2-4, dio03-3-2-2, dio03-4-1-4, dio03-4-1-2, dio08-2-3-4, dio08-2-3-2, dio06-5-3-4, dio06-5-3-2, dio08-1-3-4, dio08-1-3-2, dio08-2-2-4, dio08-2-2-2, dio08-1-4-4, dio08-1-4-2, dio08-2-1-4, dio08-2-1-2, dio08-6-1-4, dio08-6-1-2, dio08-6-3-4, dio08-6-3-2, dio03-3-1-4, dio03-3-1-2, dio05-3-1-4, dio05-3-1-2, dio05-3-3-4, dio05-3-3-2, dio05-3-2-4, dio05-3-2-2, dio05-4-1-4, dio05-4-1-2, dio05-3-4-4, dio05-3-4-2, dio05-4-2-4, dio05-4-2-2, dio06-3-4-4, dio06-3-4-2, dio06-3-1-4, dio06-3-1-2, dio09-2-2-4, dio09-2-2-2, dio08-4-3-4, dio08-4-3-2, dio03-3-3-4, dio03-3-3-2, ai13-1-8, ai10-6-6, ai13-1-4, ai13-1-6, dio05-1-7, dio05-2-7, dio05-1-6, dio05-2-8, dio05-2-5, dio05-1-8, dio05-2-6, dio05-1-5, dio06-3-7, dio06-4-5, dio06-4-8, dio06-4-6, dio06-4-7, dio06-3-6, dio06-2-6, dio06-3-8, dio06-3-5, dio06-2-8, dio06-5-5, dio06-5-6, dio03-6-7, dio03-6-5, dio03-5-6, dio03-4-7, dio03-6-8, dio03-6-6, dio05-5-5, dio06-2-7, dio06-2-5, dio06-5-7, dio08-1-7, dio08-2-7, dio08-1-8, dio08-2-6, dio08-2-5, dio06-5-8, dio06-6-7, dio06-6-8, dio08-1-5, dio08-1-6, dio06-6-5, dio06-6-6, dio05-3-5, dio05-3-7, dio05-3-8, dio05-3-6, dio05-4-5, dio05-4-6, dio05-4-7, dio05-4-8, dio05-5-6, dio05-6-5, dio05-6-6, dio05-6-7, dio03-3-6, dio03-4-5, dio03-2-5, dio03-2-6, dio03-2-7, dio03-3-5, dio03-3-7, dio09-1-8, dio09-2-6, dio08-6-5, dio08-4-7, dio08-6-7, dio09-2-5, ai07-1-1, dio08-4-5, dio08-5-7, dio08-5-6, ai07-1-3, dio09-3-7, dio08-5-5, dio09-4-5, dio09-4-7, dio09-2-8, dio09-4-6, dio09-4-8, dio09-1-7, dio09-1-6, dio03-3-8, dio03-5-5, dio03-5-7, dio03-5-8, dio09-2-7, dio09-1-5, dio09-3-6, ai07-1-4, dio09-3-5, dio08-4-8, dio09-3-8, ai07-1-2, dio08-4-6, dio08-6-6
Jan 2 19:35:22 axcf3152 Arp.System.Application: Eclr INFO - Initializing state...
Jan 2 19:35:22 axcf3152 plc-proxy[2692]: plc-proxy 2021/01/02 19:35:22.159447 dial error: dial tcp4 127.0.0.1:1999: connect: connection refused
Jan 2 19:35:22 axcf3152 plc-proxy[2692]: plc-proxy 2021/01/02 19:35:22.159518 error detected, closing TCP connection to Seq Eng
Jan 2 19:35:22 axcf3152 Arp.System.Application: Eclr INFO - Connecting to PLC Proxy via TCP/UDP...
Jan 2 19:35:22 axcf3152 Arp.System.Application: Eclr INFO - Init complete. 02.01.2021 19:35:22
Jan 2 19:35:22 axcf3152 Arp.System.Application: Eclr INFO - Listening on tcp://127.0.0.1:1999
Jan 2 19:35:22 axcf3152 Arp.System.Application: Eclr FATAL - System.Net.Sockets.SocketException: Exception of type 'System.Net.Sockets.SocketException' was thrown.
 at System.Net.Sockets.Socket.Bind : offset 001A3
 at System.Net.Sockets.TcpListener.Start : offset 0010F
 at System.Net.Sockets.TcpListener.Start : offset 0002E
 at Abl.SequenceEngine.PlcProxyConn.Listen : offset 0007C
 at Abl.SequenceEngine.SeqEng.InitAndConnect : offset 00085
Jan 2 19:35:22 axcf3152 plc-proxy[2692]: plc-proxy 2021/01/02 19:35:22.209824 dial error: dial tcp4 127.0.0.1:1999: connect: connection refused
Jan 2 19:35:22 axcf3152 plc-proxy[2692]: plc-proxy 2021/01/02 19:35:22.209893 error detected, closing TCP connection to Seq Eng

Very hard to know where to proceed--no indication what the specific error was. Nothing else should be listening on tcp:1999, just this PLCnext program.

Note that this usually works and sometimes fails, not reassuring.

Surrounding code in C#:

            tcpListenerRecvCmd = new TcpListener(IPAddress.Parse("127.0.0.1"), 1999); 
            Log(string.Format("Listening on tcp://{0}", tcpListenerRecvCmd.LocalEndpoint));
            tcpListenerRecvCmd.Start();

Advice appreciated

**Comment by martinboers** [comment]
This is a general C# question that is being handled directly with the requester.
