### ISSUE TITLE
Enums

### ISSUE THREAD

**Issue by martinboers** [PLCnext/CSharpExamples#3]
It would be interesting to see an example showing how to define and use enumerations.

**Comment by mluhmann** [comment]
You can use enums in C# and IEC 61131 as usual. They have to be defined in both worlds (probably the same) and to connect each other a port of type integer has to be used. This is different to the C++ implementation.

**Comment by martinboers** [comment]
I don't think it's necessary to define the enum in both worlds.

If a C# enum is declared with the [Enumeration] attribute (below), then it should be visible and useable in a PLCnext Engineer project, without declaring it again or connecting it using port variables.

![image](https://user-images.githubusercontent.com/13133969/138261564-b9a8f633-2fe2-4e6a-b70e-911991b52f49.png)
 
An example would clearly demonstrate the use of this attribute.

**Comment by mluhmann** [comment]
Example will be in the next update.
